allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  9a6c3439-85e1-497c-ae7e-0b0519527b3d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bbd2526b-c5cb-46ac-a3d5-20c8a96dfa0d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9126ed28-5fbe-473b-8864-726493606158 # Richtext
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 514d0e2d-0b2d-4f2e-88bd-791a7ab1b672
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ad9128cc-47be-4b3a-a7ed-d6283f4fda74
        userCondition: null
    thumbFieldKey: null
handle: accordionItem
hasTitleField: true
icon: list
name: 'Accordion Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
