allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f7c448e1-d025-4c1d-bd44-a6213d848f4c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-08-21T12:41:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 35668fdb-f65d-4c9a-b045-61e396705b91
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-21T12:41:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7e15fb59-359e-442f-96b0-a95a4e3c6bd8 # Box Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d153ff0b-5caa-4e01-b8e7-943763dd20b2
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-21T12:41:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9126ed28-5fbe-473b-8864-726493606158 # Richtext
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ea7d7a4-3eb1-4046-8627-3bfa0824056f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-08-21T12:41:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dda23604-56f0-495a-a6ed-65d381685a99 # Box Icon
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff4e82bf-baa2-40f4-ac44-8344635289b1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-21T12:41:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 62614b94-2c26-4f6f-8748-9285c22daf37 # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd3e61e4-6e6a-4c4e-9dfb-3ddfa4cdea4c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-08-21T12:41:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5e8b5399-82b0-43b4-9bea-6fc0889b9675 # CTA Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 549ef05f-338a-4ca1-b9b6-ad16823b1ac2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 697ae3e1-87b5-4188-8d06-0978d86a49c1
        userCondition: null
    thumbFieldKey: null
handle: box
hasTitleField: true
icon: square
name: Box
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
