allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  97321358-5e34-4ce6-bacf-6f4f97cb0c6a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 65e99bf9-c856-4dd7-898f-eb8c935bad12
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 62614b94-2c26-4f6f-8748-9285c22daf37 # Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 842e8755-4e2f-4632-a126-38d75dab8c87
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2a2bd160-f2fe-4202-9ebe-66e5cb732217 # Download File
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09761563-d812-4ae4-8b09-f06d2c387237
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9126ed28-5fbe-473b-8864-726493606158 # Richtext
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 721cbe13-5163-4a24-a6f5-edc24407c58f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c0b402c5-966c-4283-a011-413b1095969d # Download Button Label
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e83f48ae-2a8f-49cd-9056-04ee8db9ec84
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9f52dd8e-3d45-4b88-8332-7fd1462652fa
        userCondition: null
    thumbFieldKey: null
handle: download
hasTitleField: true
icon: download
name: Download
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
