allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  44a2f988-1958-4a12-8820-b4a70087ae11:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f289e510-088a-47da-a86a-7c57bd5143f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6b4b5506-4547-4ce8-a097-175326f62438 # Hero Statement
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a34839f-0b71-4bd6-a88d-91e9be3d0c3e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 86bdf1c6-40a2-45a8-b62f-eb1162f3fb34 # Lead Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3196aa4d-2735-44c8-a6ff-5b3e8eed6351
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8b634a68-f395-496d-85d1-7519546717e8 # Content Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eedb1b0-7181-456d-ae26-43b75e8ab788
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dd6f1dd8-f2a8-47a3-8e02-11b1b555461f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 83bdf192-e837-424f-b13b-d3e71f3f4199 # SEO Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b6fa53a-4d2e-4f3c-97ae-49b26a229197
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b77edfd0-043c-470a-9805-e7d2e8ab1ddf # SEO Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d66dece-1175-4a83-add6-f2cb008f8c4c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b4d031c7-71f2-4bee-8af6-f59b78287348
        userCondition: null
    thumbFieldKey: null
handle: home
hasTitleField: true
icon: house
name: Home
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
