allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  fffbcbcc-ddcc-49bf-a9ef-b0850b2dccf8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e8fc113e-9c00-4f14-8a0d-69190f56ec6d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d97c0326-e5c2-4615-8e72-0e53c3a6b957 # Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0439fe3c-f779-4904-9781-c2cc08793f86
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eb977b50-4a60-46e4-91eb-67de273c9819
        userCondition: null
    thumbFieldKey: null
handle: linkItem
hasTitleField: true
icon: link
name: 'Link Item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
