allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  a1158e5b-0fd2-47a1-8f05-1a74a5d29b31:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3dd30f7f-bea1-4a6c-b168-b4aaf93e14b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 86bdf1c6-40a2-45a8-b62f-eb1162f3fb34 # Lead Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14184eeb-3b1c-4b1c-8bad-15bb54270ec2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8b634a68-f395-496d-85d1-7519546717e8 # Content Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fbd9f19-dc44-4d63-a890-0c3c6deda0fb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ccaa5979-4d9b-4a61-8388-167cefee95b2
        userCondition: null
    thumbFieldKey: null
handle: topicPage
hasTitleField: true
icon: file-lines
name: 'Topic Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
