altTranslationKeyFormat: null
altTranslationMethod: none
fs: r2
handle: assets
name: Assets
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
