altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  adf495c1-088a-4956-9a5f-2fcee562ae79:
    tabs: []
fs: r2
handle: assets
name: Assets
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
