columnSuffix: null
handle: ctaLink
instructions: null
name: 'CTA Link'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: true
  types:
    - entry
    - url
    - asset
translationKeyFormat: null
translationMethod: site
type: craft\fields\Link
