columnSuffix: null
handle: imageFit
instructions: null
name: 'Image Fit'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Cover
        -
          - value
          - cover
        -
          - icon
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Contain
        -
          - value
          - contain
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Cover (Match Row Height)'
        -
          - value
          - coverMatchHeight
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
