columnSuffix: null
handle: seoDescription
instructions: 'Optional search and social description. Keep it concise; lead text is used as a fallback.'
name: 'SEO Description'
searchable: false
settings:
  byteLimit: null
  charLimit: 160
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
